In [13]:
from tensorflow.keras.models import load_model #for loading the model that we have created
import pickle
import pandas as pd
import tensorflow as tf

In [14]:
with open('label_encoder.pkl','rb') as file:
    label=pickle.load(file)

In [15]:
with open('onehot_encoder.pkl','rb') as file:
    onehot=pickle.load(file)

In [16]:
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [17]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [18]:
user={'Pclass':3,'Sex':'female','SibSp':1,'Parch':1,'Fare':11,'Embarked':'Queenstown'} #Enter user data to predict the survival.

In [19]:
user=pd.DataFrame([user])

In [20]:
user

   Pclass     Sex  SibSp  Parch  Fare    Embarked
0       3  female      1      1    11  Queenstown

In [21]:
user['Sex']=label.transform(user['Sex']) #fit transform we use when we are first time encoding the data but here we are using the same process we used in training to just transform the user data.

In [22]:
embarked=onehot.transform(user[['Embarked']])

In [24]:
embarked=pd.DataFrame(embarked,columns=onehot.get_feature_names_out())

In [26]:
user=pd.concat([user.drop(columns=['Embarked']),embarked],axis=1)

In [27]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,3,0,1,1,11,0.0,1.0,0.0

In [28]:
user[['Pclass','SibSp','Parch','Fare']]=scaler.transform(user[['Pclass','SibSp','Parch','Fare']])

In [29]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,0.824107,0,0.442462,0.833802,-0.458638,0.0,1.0,0.0

In [ ]:
y=model.predict(user) #model will predict probability because it is a classification problem.

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 717ms/step

In [32]:
y=y[0][0]

In [33]:
if y>0.5:
    print("The passenger will survive")
else:
    print("The passenger will not survive")

The passenger will not survive