In [23]:
# Data Gathering

In [24]:
import pandas as pd

In [25]:
data=pd.read_csv('ai_dev_productivity.csv')

In [26]:
data.shape #It is very less data for a DL Model. But for working on CPU and for understanding we can use this.

(500, 9)

In [27]:
data.head()

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
0,5.99,600,1,5.8,2,1,0.71,5.4,1
1,4.72,568,2,6.9,5,3,1.75,4.7,1
2,6.30,560,1,8.9,2,0,2.27,2.2,1
3,8.05,600,7,6.3,9,5,1.40,5.9,0
4,4.53,421,6,6.9,4,0,1.26,6.3,1

# Data Preprocessing

In [28]:
data.isnull().sum()

hours_coding        0
coffee_intake_mg    0
distractions        0
sleep_hours         0
commits             0
bugs_reported       0
ai_usage_hours      0
cognitive_load      0
task_success        0
dtype: int64

In [29]:
data.duplicated().sum()

np.int64(0)

In [30]:
data.info() #whether consisting of proper datatypes or not

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hours_coding      500 non-null    float64
 1   coffee_intake_mg  500 non-null    int64
 2   distractions      500 non-null    int64
 3   sleep_hours       500 non-null    float64
 4   commits           500 non-null    int64
 5   bugs_reported     500 non-null    int64
 6   ai_usage_hours    500 non-null    float64
 7   cognitive_load    500 non-null    float64
 8   task_success      500 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [31]:
data.describe() #for regression we will use cognitive_load, for classification problems we might have used task_success.

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,cognitive_load,task_success
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000
mean,5.015600,463.192000,2.976000,6.975800,4.60800,0.858000,1.510920,4.498200,0.606000
std,1.947253,142.334991,1.678409,1.455965,2.70499,1.102846,1.085557,1.868861,0.489124
min,0.000000,6.000000,0.000000,3.000000,0.00000,0.000000,0.000000,1.000000,0.000000
25%,3.600000,369.500000,2.000000,6.100000,3.00000,0.000000,0.697500,3.175000,0.000000
50%,5.030000,500.500000,3.000000,6.950000,5.00000,0.000000,1.260000,4.400000,1.000000
75%,6.275000,600.000000,4.000000,7.900000,6.00000,2.000000,2.070000,5.800000,1.000000
max,12.000000,600.000000,8.000000,10.000000,13.00000,5.000000,6.360000,10.000000,1.000000

# data cleaning is not required as there is no null,duplicated or missing values, or improper datatypes. data encoding is also not required as all are present in numerical values only.

# Train Test Split

In [32]:
X=data.drop(['cognitive_load'],axis=1) #independent variables
Y=data['cognitive_load'] #dependent variable

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42) #we will not use validation data as we have very less data here. We are only trying to understand regression here.

In [35]:
X_train.shape

(400, 8)

# Scaling

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
scale=StandardScaler()

In [38]:
X_train[['hours_coding','coffee_intake_mg','distractions','sleep_hours','commits','bugs_reported','ai_usage_hours']] = scale.fit_transform(X_train[['hours_coding','coffee_intake_mg','distractions','sleep_hours','commits','bugs_reported','ai_usage_hours']]) #we apply scaling onto continuous columns and not binary columns like task_success. We will not scale the target variable(cognitive_load) as it is a regression problem and we want to predict the actual value of cognitive_load.

In [39]:
X_test[['hours_coding','coffee_intake_mg','distractions','sleep_hours','commits','bugs_reported','ai_usage_hours']] = scale.transform(X_test[['hours_coding','coffee_intake_mg','distractions','sleep_hours','commits','bugs_reported','ai_usage_hours']]) #we apply scaling onto continuous columns and not binary columns like task_success. We will not scale the target variable(cognitive_load) as it is a regression problem and we want to predict the actual value of cognitive_load. Here only transform is used as we have already fitted the scaler on training data and we want to use the same scaling parameters on test data.

In [40]:
X_train

,hours_coding,coffee_intake_mg,distractions,sleep_hours,commits,bugs_reported,ai_usage_hours,task_success
249,0.410116,0.348814,-1.159772,1.628183,0.146206,-0.780969,0.050837,1
433,0.731716,0.508152,1.222301,-0.459879,-1.334364,-0.780969,0.634796,1
19,-1.442912,-1.424697,0.031265,-2.211156,-0.594079,-0.780969,-0.778007,0
322,-0.840550,-0.066853,0.031265,-0.527236,-0.964221,1.927593,0.493516,0
332,0.073202,0.030136,1.222301,-0.729306,-0.594079,-0.780969,0.465260,0
...,...,...,...,...,...,...,...,...
106,1.921126,0.965386,-0.564254,0.348403,0.146206,-0.780969,-0.420097,1
270,1.466802,0.965386,2.413338,1.224042,1.256634,-0.780969,0.041419,1
348,-0.738455,-0.946681,-0.564254,-0.594592,-0.223936,1.024739,-1.201848,0
435,0.073202,0.203330,-0.564254,1.156685,1.256634,-0.780969,-0.307073,1
102,-0.355598,0.099414,-1.159772,-0.998733,-0.594079,-0.780969,-0.373004,1

# data leakage
If we scale the data before train test split then the mean of entire data is calculated which has both training and testing, so training data scaling is influenced by testing data also. which leads in leakage of information. We cannot figure whether the model has learned perfectly or was already influenced initially. Hence we split the data first and apply scaling to only training data(fit.transform) and onto test data we only apply the transformation as done in training data not fit. Basically as per the rules set in training data(mean value and std deviation), we apply the same onto test data. It is always a good practice to split data into train test first and then scaling. We scale not column by column but the entire dataset to get the mean value and std value of entire dataset and then subtracting every value from mean(of entire dataset)/std value(entire dataset), in this way only we can form a similar range between all values.

# Model Building

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
model=Sequential([Dense(64,input_shape=(X_train.shape[1],)),Dense(32,activation='linear'),Dense(1,activation='linear')]) #we will not create a complex network here because we have very less data and will result in overfitting. In regression problem we use linear activation function as we don't need to shrink any output value. we want continuous output values not probability scores. So not mentioning any activation function is synonymous to using linear(does not introduce non linearity to output like sigmoid,relu etc did) activation function. If we don't use activation finction like relu in the hidden layers then model will collpase in linear model. It can still learn or make predictions but cannot predict complex patterns. Like if house prices are increasing non linearly like small house price increase slowly,medium house rapidly and huge house  differently again, linear model will predict something like house size increases pice increases at a constant rate. So ofc depends upon the use case if you want to use relu in hidden layers or not.

c:\Users\Somya Goyal\Downloads\ANN Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [43]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(optimizer='adam',metrics=['mae'],loss='mse') #we use mean squared error as loss function for regression problems. We can also use mean absolute error as loss function. But MSE is more sensitive to outliers and we want to penalize the model more for large errors.

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [46]:
model.fit(X_train,Y_train,epochs=100) #for less data here we can use 100 epochs

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 22.7769 - mae: 4.4615
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.5425 - mae: 3.7600
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.8933 - mae: 2.9750
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.2963 - mae: 2.1388
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.5502 - mae: 1.4993
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7971 - mae: 1.3362
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.6501 - mae: 1.3127
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.4628 - mae: 1.2620
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3429 - mae: 1.2220
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.2128 - mae: 1.1862
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0992 - mae: 1.1606
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0069 - mae: 1.1405
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.8756 - mae: 1.1041
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.7862 - mae: 1.0749
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6942 - mae: 1.0466
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5948 - mae: 1.0195
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5126 - mae: 0.9942
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4529 - mae: 0.9698
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.3661 - mae: 0.9408
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3089 - mae: 0.9250
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.2523 - mae: 0.9008
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2077 - mae: 0.8810
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1496 - mae: 0.8561
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1214 - mae: 0.8445
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0922 - mae: 0.8325
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0635 - mae: 0.8166
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0413 - mae: 0.8113
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0390 - mae: 0.8070
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0099 - mae: 0.7965
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0263 - mae: 0.8045
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0182 - mae: 0.7934
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0071 - mae: 0.7924
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.9794 - mae: 0.7832
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9882 - mae: 0.7866
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9853 - mae: 0.7859
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9887 - mae: 0.7878
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9967 - mae: 0.7923
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9833 - mae: 0.7840
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9904 - mae: 0.7862
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9840 - mae: 0.7843
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9840 - mae: 0.7881
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9813 - mae: 0.7841
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9816 - mae: 0.7792
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9993 - mae: 0.7943
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0016 - mae: 0.7941
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9734 - mae: 0.7813
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9758 - mae: 0.7823
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9807 - mae: 0.7833
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9841 - mae: 0.7855
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0041 - mae: 0.7997
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9896 - mae: 0.7873
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9808 - mae: 0.7804
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9815 - mae: 0.7843
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9978 - mae: 0.7961
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9934 - mae: 0.7882
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9807 - mae: 0.7883
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0105 - mae: 0.7932
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0004 - mae: 0.7922
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9651 - mae: 0.7783
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0009 - mae: 0.7969
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9928 - mae: 0.7851
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9845 - mae: 0.7872
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9717 - mae: 0.7831
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9760 - mae: 0.7827
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9860 - mae: 0.7863
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9960 - mae: 0.7941
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9920 - mae: 0.7890
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9943 - mae: 0.7946
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9970 - mae: 0.7915
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9882 - mae: 0.7827
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0126 - mae: 0.8007
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9865 - mae: 0.7880
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9917 - mae: 0.7882
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9770 - mae: 0.7829
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9803 - mae: 0.7871
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9829 - mae: 0.7842
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9859 - mae: 0.7837
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0051 - mae: 0.7910
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9911 - mae: 0.7901
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0227 - mae: 0.8043
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9942 - mae: 0.7920
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9908 - mae: 0.7902
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0075 - mae: 0.7985
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0122 - mae: 0.8025
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0041 - mae: 0.7918
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9835 - mae: 0.7822
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9839 - mae: 0.7840
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0161 - mae: 0.7960
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0002 - mae: 0.7861
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9843 - mae: 0.7860
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0053 - mae: 0.7972
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0023 - mae: 0.7995
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9911 - mae: 0.7866
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9829 - mae: 0.7824
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0032 - mae: 0.7873
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9841 - mae: 0.7876
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9761 - mae: 0.7832
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9855 - mae: 0.7888
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0010 - mae: 0.7915
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9864 - mae: 0.7864

In [47]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [48]:
Y_predict=model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step

In [ ]:
mean_squared_error(Y_predict,Y_test) #In regression problems, there is no accuracy score like classification problems. So we use metrics like mean squared error, mean absolute error and r2 score to evaluate the model performance. It shows how far my predictions are from the actual values. The lower the value of MSE and MAE, the better the model performance. The higher the value of r2 score, the better the model performance. The best value of r2 score is 1 and worst is 0. It can also be negative if the model is performing worse than a horizontal line. With this high mse there could be overfitting but we just want to understand regression.

0.8614255399816431

# Hyperparameter Tuning
If the model is not giving good accuracy we can go with hyperparameter tuning in which we can use 1)KerasClassifier 2)KerasTuner. Through this we can make changes or tune some hyperparameters like optimizers,loss function,activation functions, no of hidden layers, number of perceptrons/nodes in hidden layer,dropout value(0.1,0.2,0.3 etc). Because we need to check and update parameters we can go with GPU(Google Colab). Choose T4 GPU as a runtime. Always save files before shutting or sleeping laptop as in runtime, files will be deleted as the laptop or internet is off or the runtime is terminated.