#### 1)Define the problem statement into a ML problem statement like defining the input and output etc.

#### 2)Data Gathering:-csv,database(json),api,web scraping

In [3]:
#### import all the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\Somya Goyal\anaconda3\envs\genai\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Somya Goyal\anaconda3\envs\genai\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Somya Goyal\anaconda3\envs\genai\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\Users\Somya Goyal\anaconda3\envs\genai\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\Somya Goyal\anaconda3\envs\genai\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
df=pd.read_csv('International_Education_Costs.csv')

In [5]:
df.head()

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
0,USA,Cambridge,Harvard University,Computer Science,Master,2.0,55400,83.5,2200,160,1500,1.00
1,UK,London,Imperial College London,Data Science,Master,1.0,41200,75.8,1800,485,800,0.79
2,Canada,Toronto,University of Toronto,Business Analytics,Master,2.0,38500,72.5,1600,235,900,1.35
3,Australia,Melbourne,University of Melbourne,Engineering,Master,2.0,42000,71.2,1400,450,650,1.52
4,Germany,Munich,Technical University of Munich,Mechanical Engineering,Master,2.0,500,70.5,1100,75,550,0.92

#### 3)Data Exploration,preprocessing and cleaning

In [6]:
df.describe()

,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
count,907.000000,907.000000,907.000000,907.000000,907.000000,907.000000,907.000000
mean,2.836825,16705.016538,64.437486,969.206174,211.396913,700.077178,623.000695
std,0.945449,16582.385275,14.056333,517.154752,143.435740,320.374875,3801.746134
min,1.000000,0.000000,27.800000,150.000000,40.000000,200.000000,0.150000
25%,2.000000,2850.000000,56.300000,545.000000,100.000000,450.000000,0.920000
50%,3.000000,7500.000000,67.500000,900.000000,160.000000,650.000000,1.350000
75%,4.000000,31100.000000,72.200000,1300.000000,240.000000,800.000000,7.150000
max,5.000000,62000.000000,122.400000,2500.000000,490.000000,1500.000000,42150.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            907 non-null    str
 1   City               907 non-null    str
 2   University         907 non-null    str
 3   Program            907 non-null    str
 4   Level              907 non-null    str
 5   Duration_Years     907 non-null    float64
 6   Tuition_USD        907 non-null    int64
 7   Living_Cost_Index  907 non-null    float64
 8   Rent_USD           907 non-null    int64
 9   Visa_Fee_USD       907 non-null    int64
 10  Insurance_USD      907 non-null    int64
 11  Exchange_Rate      907 non-null    float64
dtypes: float64(3), int64(4), str(5)
memory usage: 135.6 KB

Using pandas features for this step like min,max,astype,isnull etc

#### 4) Exploratory data analysis
Univariate and Bivariate Analysis using matplotlib and seaborn

#### 5)Feature Engineering and feature selection

In [ ]:
df['Total_cost']=df['Tuition_USD']+df['Rent_USD'] #Addition of new feature column to the dataset through existing feature columns.

In [10]:
df

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate,Total_cost
0,USA,Cambridge,Harvard University,Computer Science,Master,2.0,55400,83.5,2200,160,1500,1.00,57600
1,UK,London,Imperial College London,Data Science,Master,1.0,41200,75.8,1800,485,800,0.79,43000
2,Canada,Toronto,University of Toronto,Business Analytics,Master,2.0,38500,72.5,1600,235,900,1.35,40100
3,Australia,Melbourne,University of Melbourne,Engineering,Master,2.0,42000,71.2,1400,450,650,1.52,43400
4,Germany,Munich,Technical University of Munich,Mechanical Engineering,Master,2.0,500,70.5,1100,75,550,0.92,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
902,France,Strasbourg,University of Strasbourg,Data Analytics,Master,2.0,4000,70.2,1000,99,850,0.92,5000
903,Malaysia,Nilai,USIM,Computer Science,Bachelor,3.0,6800,50.5,400,120,400,4.65,7200
904,Saudi Arabia,Al-Ahsa,King Faisal University,Information Systems,Master,2.0,4200,64.2,600,200,800,3.75,4800
905,USA,Seattle,University of Washington,Software Development,PhD,5.0,50000,77.8,2000,160,1500,1.00,52000
906,UK,Nottingham,University of Nottingham,Data Engineering,Master,2.0,34000,61.2,800,485,800,0.79,34800

In [19]:
## Feature selection is selection of only those features that are much relevant to the output.
df=df[['Country','City','University','Program','Level','Duration_Years','Living_Cost_Index','Visa_Fee_USD','Insurance_USD','Total_cost']]

In [20]:
df

,Country,City,University,Program,Level,Duration_Years,Living_Cost_Index,Visa_Fee_USD,Insurance_USD,Total_cost
0,66,Cambridge,Harvard University,Computer Science,Master,2.0,83.5,160,1500,57600
1,65,London,Imperial College London,Data Science,Master,1.0,75.8,485,800,43000
2,9,Toronto,University of Toronto,Business Analytics,Master,2.0,72.5,235,900,40100
3,2,Melbourne,University of Melbourne,Engineering,Master,2.0,71.2,450,650,43400
4,22,Munich,Technical University of Munich,Mechanical Engineering,Master,2.0,70.5,75,550,1600
...,...,...,...,...,...,...,...,...,...,...
902,21,Strasbourg,University of Strasbourg,Data Analytics,Master,2.0,70.2,99,850,5000
903,38,Nilai,USIM,Computer Science,Bachelor,3.0,50.5,120,400,7200
904,51,Al-Ahsa,King Faisal University,Information Systems,Master,2.0,64.2,200,800,4800
905,66,Seattle,University of Washington,Software Development,PhD,5.0,77.8,160,1500,52000
906,65,Nottingham,University of Nottingham,Data Engineering,Master,2.0,61.2,485,800,34800

#### 6)Label Encoding/Feature Encoding
is required to convert categorical column to numerical column because we are feeding it into our mathematical model.

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le=LabelEncoder()

In [21]:
df['Country']=le.fit_transform(df['Country'])
df['City']=le.fit_transform(df['City'])
df['University']=le.fit_transform(df['University'])
df['Program']=le.fit_transform(df['Program'])
df['Level']=le.fit_transform(df['Level'])

In [22]:
df.head()
#here categorical column is converted in numeric column, similar we can do for other categorical columns as well.

,Country,City,University,Program,Level,Duration_Years,Living_Cost_Index,Visa_Fee_USD,Insurance_USD,Total_cost
0,66,84,101,17,1,2.0,83.5,160,1500,57600
1,65,283,128,27,1,1.0,75.8,485,800,43000
2,9,503,572,9,1,2.0,72.5,235,900,40100
3,2,313,495,44,1,2.0,71.2,450,650,43400
4,22,330,307,66,1,2.0,70.5,75,550,1600

#### 7)Separate Input Column from Output Column
separate input feature columns and output column

In [23]:
x=df.iloc[:, :9] #all rows and columns from inded 0 to 8(before 9 all selected)
y=df['Total_cost']

In [24]:
x

,Country,City,University,Program,Level,Duration_Years,Living_Cost_Index,Visa_Fee_USD,Insurance_USD
0,66,84,101,17,1,2.0,83.5,160,1500
1,65,283,128,27,1,1.0,75.8,485,800
2,9,503,572,9,1,2.0,72.5,235,900
3,2,313,495,44,1,2.0,71.2,450,650
4,22,330,307,66,1,2.0,70.5,75,550
...,...,...,...,...,...,...,...,...,...
902,21,469,556,25,1,2.0,70.2,99,850
903,38,344,345,17,0,3.0,50.5,120,400
904,51,12,154,57,1,2.0,64.2,200,800
905,66,441,585,84,2,5.0,77.8,160,1500
906,65,347,512,26,1,2.0,61.2,485,800

In [25]:
y

0      57600
1      43000
2      40100
3      43400
4       1600
       ...
902     5000
903     7200
904     4800
905    52000
906    34800
Name: Total_cost, Length: 907, dtype: int64

#### 8)Feature Scaling
All column values must come in similar range

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
s=StandardScaler()

In [ ]:
x=s.fit_transform(x) #that's why column separation was done before so that we can pass the entire dataframe at once without writing down all the column names.

In [ ]:
x #we want our model to predict exact output value so we don;t scale output column, only input so that it comes at a same range or scale and model can predict better results.

array([[ 1.29937861, -1.18314994, -1.25623694, ...,  1.35689951,
        -0.3585248 ,  2.49821139],
       [ 1.25678296,  0.02539721, -1.10697039, ...,  0.80880148,
         1.90854833,  0.31206552],
       [-1.12857335,  1.3614795 ,  1.3476352 , ...,  0.57390232,
         0.16464592,  0.62437207],
       ...,
       [ 0.66044389, -1.62041323, -0.96323222, ..., -0.01690464,
        -0.07950042,  0.31206552],
       [ 1.29937861,  0.98494722,  1.41950429, ...,  0.9511646 ,
        -0.3585248 ,  2.49821139],
       [ 1.25678296,  0.4140757 ,  1.01593175, ..., -0.23044933,
         1.90854833,  0.31206552]], shape=(907, 9))

#### 9)Train test splitting
80% for training and 20% for testing for both input and output data

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42) #80% data for training and 20% data for testing the model. test is 20% so test_size=0.2, random_state is used to get same split of data every time we run the code.

In [34]:
x_train.shape

(725, 9)

In [35]:
x_test.shape

(182, 9)

In [36]:
y_train.shape

(725,)

In [37]:
y_test.shape

(182,)

#### 10)Model training and Evaluation
Different Algorithms for different use cases. choose what is best for each use case.

In [38]:
###Regression
# 1)Linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [39]:
lr.fit(x_train,y_train)

LinearRegression()

In [41]:
y_predict=lr.predict(x_test)

In [42]:
#Evaluation of how much correct or accurate our model is:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

8659.427341273544

In [44]:
mean_squared_error(y_test,y_predict) #mean squared error is the average of squared difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

130433373.64519891

In [45]:
## 2)Ridge Algo
from sklearn.linear_model import Ridge
r=Ridge(alpha=0.1) #alpha is the regularization parameter, it is used to control the complexity of the model. It helps to prevent overfitting. It is a hyperparameter that can be tuned to get the best results.

In [46]:
r.fit(x_train,y_train)

Ridge(alpha=0.1)

In [48]:
y_predict=r.predict(x_test)

In [49]:
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

8659.433012802261

In [50]:
##3)Lasso Algo
from sklearn.linear_model import Lasso

In [51]:
l=Lasso(alpha=0.1) #alpha is the regularization parameter, it is used to control the complexity of the model. It helps to prevent overfitting. It is a hyperparameter that can be tuned to get the best results.

In [52]:
l.fit(x_train,y_train)

Lasso(alpha=0.1)

In [53]:
y_predict=l.predict(x_test)

In [54]:
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

8659.426292390086

In [55]:
##4)ElasticNet Algo
from sklearn.linear_model import ElasticNet

In [63]:
e=ElasticNet(alpha=0.1,l1_ratio=0.5) #alpha is the regularization parameter, it is used to control the complexity of the model. It helps to prevent overfitting. It is a hyperparameter that can be tuned to get the best results. l1_ratio is the ratio of L1 and L2 regularization, it is used to control the balance between L1 and L2 regularization.

In [62]:
e.fit(x_train,y_train)

ElasticNet(alpha=0.1)

In [61]:
y_predict=e.predict(x_test)

In [64]:
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

8742.362441841186

In [65]:
##5)Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor

In [66]:
tree=DecisionTreeRegressor(max_depth=5) #max_depth is the maximum depth of the tree. It is used to control the complexity of the model. It helps to prevent overfitting. It is a hyperparameter that can be tuned to get the best results.

In [67]:
tree.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=5)

In [69]:
y_predict=tree.predict(x_test)

In [70]:
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

4214.62049327467

In [77]:
##6)Random Forest Regressor(Combination of Multiple ALgo(Decision tree))

from sklearn.ensemble import RandomForestRegressor


rf=RandomForestRegressor(n_estimators=100) #n_estimators is the number of trees in the forest. It is a hyperparameter that can be tuned to get the best results.
rf.fit(x_train,y_train)
y_predict=rf.predict(x_test)
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

2636.5210622710624

## Ensemble Learning---->XGBoost,AdaBoost,CatBoost Regressor

In [72]:
from sklearn.ensemble import AdaBoostRegressor

ada=AdaBoostRegressor(n_estimators=100) #n_estimators is the number of weak learners in the ensemble. It is a hyperparameter that can be tuned to get the best results.
ada.fit(x_train,y_train)
y_predict=ada.predict(x_test)
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

5700.222941581917

In [73]:
##Kneighbors Regressor--->neighbour data points--->neighbours prediction---->closer prediction
from sklearn.neighbors import KNeighborsRegressor

knn=KNeighborsRegressor(n_neighbors=5) #n_neighbors is the number of neighbors to use for predictions. It is a hyperparameter that can be tuned to get the best results.
knn.fit(x_train,y_train)
y_predict=knn.predict(x_test)
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

5825.32967032967

In [74]:
##Support Vector Regressor


from sklearn.svm import SVR


svr=SVR(kernel='rbf') #kernel is the type of function used to map the data into a higher dimensional space. It is a hyperparameter that can be tuned to get the best results.
svr.fit(x_train,y_train)
y_predict=svr.predict(x_test)
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.

14308.751937241615

In [ ]:
##Bagging Regressor
from sklearn.ensemble import BaggingRegressor

bag=BaggingRegressor(n_estimators=100) #n_estimators is the number of base estimators in the ensemble. It is a hyperparameter that can be tuned to get the best results.
bag.fit(x_train,y_train)
y_predict=bag.predict(x_test)
mean_absolute_error(y_test,y_predict) #mean absolute error is the average of absolute difference between actual and predicted values. It gives us an idea of how much our model is off from the actual value on average. #Here it is quite a huge value so we will use another algorithm for better prediction.
#least error found through this algorithm so we will use this algorithm for our final model.

2616.5998168498168

In [ ]:
##Stacking Regressor--->ensemble learning---->combination of multiple models of our own choice
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import BaggingRegressor

estimators = [
    ('rf', RandomForestRegressor()),
    ('br', BaggingRegressor())
]

stack = StackingRegressor(
    estimators=estimators,
    final_estimator=DecisionTreeRegressor()
)
stack.fit(x_train, y_train)

y_predict = stack.predict(x_test)

from sklearn.metrics import mean_absolute_error

mean_absolute_error(y_test, y_predict)
#basically here random forest and bagging regressor are used as base models(less error was found in it) and decision tree is used as final model. This is a combination of multiple models to get better results.

4361.593406593406

## In classification also we have many algorithms and evaluation metrices.

In [ ]:
##Similar steps till train test split
#1)Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Create Model
lr = LogisticRegression()

# Train Model
lr.fit(X_train, y_train)

# Predict
y_predict = lr.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)
#result:0.72 means 72% accuracy

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Create Model
tree = DecisionTreeClassifier(max_depth=5)

# Train Model
tree.fit(X_train, y_train)

# Predict
y_predict = tree.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create Model
forest = RandomForestClassifier(n_estimators=100)

# Train Model
forest.fit(X_train, y_train)

# Predict
y_predict = forest.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

XGB,ADA,Catboost classifier here also

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Create Model
KNN = KNeighborsClassifier(n_neighbors=5)

# Train Model
KNN.fit(X_train, y_train)

# Predict
y_predict = KNN.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

In [ ]:
## Support Vector Classifier(draws hyperplane between two classes for classification)
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Create Model
svc = SVC(kernel='rbf')

# Train Model
svc.fit(X_train, y_train)

# Predict
y_predict = svc.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

In [ ]:
## Naive Bayes-->Bernoulli,Multinomial Naive Bayes
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# Create Model
bn = BernoulliNB()

# Train Model
bn.fit(X_train, y_train)

# Predict
y_predict = bn.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score

# Create Model
bag = BaggingClassifier(n_estimators=100)

# Train Model
bag.fit(X_train, y_train)

# Predict
y_predict = bag.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

# Base Models
estimators = [
    ('rf', RandomForestClassifier()),
    ('bc', BaggingClassifier())
]

# Stacking Model
stack = StackingClassifier(
    estimators=estimators,
    final_estimator=AdaBoostClassifier()
)

# Train Model
stack.fit(X_train, y_train)

# Predict
y_predict = stack.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_predict)

print("Accuracy:", accuracy)

#### Hyperparameter Tuning--->GridSearchCV,RandomSearchCV
parameters passed inside algorithms like estimators etc, if we increase their value will we result in better accuracy?

In [79]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# Parameter Grid
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [4, 6, 8]
}

# Grid Search
grid = GridSearchCV(
    estimator=RandomForestRegressor(),
    param_grid=param_grid,
    cv=5
)

# Train
grid.fit(x_train, y_train)

# Best Parameters
print(grid.best_params_)

# Best Cross-Validation Score
print(grid.best_score_)

{'max_depth': 8, 'n_estimators': 100}
0.9265733525788964

In [81]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

# Parameter Distribution
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [4, 6, 8]
}

# Randomized Search
random = RandomizedSearchCV(
    estimator=RandomForestRegressor(),
    param_distributions=param_grid,
    n_iter=10,
    cv=5
)

# Train
random.fit(x_train, y_train)

# Best Parameters
print(random.best_params_)

# Best Cross-Validation Score
print(random.best_score_)

c:\Users\Somya Goyal\anaconda3\envs\genai\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

{'n_estimators': 100, 'max_depth': 8}
0.9280900223188085

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Create Model
model = RandomForestRegressor(n_estimators=200)

# Train Model
model.fit(x_train, y_train)

# Predict
y_predict = model.predict(x_test)

# Mean Absolute Error
mae = mean_absolute_error(y_test, y_predict)

print("MAE:", mae)
#so basically here we use the tuned parameters from the grid search and random search to train the model and get the best results from our random forest model.

MAE: 2709.6628205128204

#### Deployment--->final stage
so our final model is converted into proper file

In [ ]:
import pickle

# Save the trained model
with open('model.pkl', 'wb') as file:
    pickle.dump(model, file)

# Load the saved model
with open('model.pkl', 'rb') as file:
    new_model = pickle.load(file)

# Display the loaded model
print(new_model)

# Make predictions using the loaded model
y_predict = new_model.predict()
#by entering values of input features in the predict() function we can get the predicted output value from the model.
#model.pkl is our final project model which can be used to predict the output value for any input values of features.

RandomForestRegressor(n_estimators=200)
2709.6628205128204